# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: control_relay_service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='control_relay_service.proto',
  package='control_relay_service.v1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1b\x63ontrol_relay_service.proto\x12\x18\x63ontrol_relay_service.v1\x1a\x1bgoogle/protobuf/empty.proto\"\x11\n\x0f\x43ontrollerHello\"\"\n\x0b\x44\x65viceHello\x12\x13\n\x0b\x64\x65vice_name\x18\x01 \x01(\t\"\xa0\x01\n\x0cHelloRequest\x12?\n\ncontroller\x18\x01 \x01(\x0b\x32).control_relay_service.v1.ControllerHelloH\x00\x12\x37\n\x06\x64\x65vice\x18\x02 \x01(\x0b\x32%.control_relay_service.v1.DeviceHelloH\x00\x42\x16\n\x14local_endpoint_hello\"\xa2\x01\n\rHelloResponse\x12?\n\ncontroller\x18\x01 \x01(\x0b\x32).control_relay_service.v1.ControllerHelloH\x00\x12\x37\n\x06\x64\x65vice\x18\x02 \x01(\x0b\x32%.control_relay_service.v1.DeviceHelloH\x00\x42\x17\n\x15remote_endpoint_hello\"m\n\x12\x43ontrolRelayPacket\x12\x13\n\x0b\x64\x65vice_name\x18\x01 \x01(\t\x12\x18\n\x10\x64\x65vice_interface\x18\x02 \x01(\t\x12\x18\n\x10originating_rule\x18\x03 \x01(\t\x12\x0e\n\x06packet\x18\n \x01(\x0c\x32v\n\x18\x43ontrolRelayHelloService\x12Z\n\x05Hello\x12&.control_relay_service.v1.HelloRequest\x1a\'.control_relay_service.v1.HelloResponse\"\x00\x32\xce\x01\n\x19\x43ontrolRelayPacketService\x12R\n\x08PacketTx\x12,.control_relay_service.v1.ControlRelayPacket\x1a\x16.google.protobuf.Empty\"\x00\x12]\n\x11ListenForPacketRx\x12\x16.google.protobuf.Empty\x1a,.control_relay_service.v1.ControlRelayPacket\"\x00\x30\x01\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_CONTROLLERHELLO = _descriptor.Descriptor(
  name='ControllerHello',
  full_name='control_relay_service.v1.ControllerHello',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=103,
)


_DEVICEHELLO = _descriptor.Descriptor(
  name='DeviceHello',
  full_name='control_relay_service.v1.DeviceHello',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_name', full_name='control_relay_service.v1.DeviceHello.device_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=139,
)


_HELLOREQUEST = _descriptor.Descriptor(
  name='HelloRequest',
  full_name='control_relay_service.v1.HelloRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='controller', full_name='control_relay_service.v1.HelloRequest.controller', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='device', full_name='control_relay_service.v1.HelloRequest.device', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='local_endpoint_hello', full_name='control_relay_service.v1.HelloRequest.local_endpoint_hello',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=142,
  serialized_end=302,
)


_HELLORESPONSE = _descriptor.Descriptor(
  name='HelloResponse',
  full_name='control_relay_service.v1.HelloResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='controller', full_name='control_relay_service.v1.HelloResponse.controller', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='device', full_name='control_relay_service.v1.HelloResponse.device', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='remote_endpoint_hello', full_name='control_relay_service.v1.HelloResponse.remote_endpoint_hello',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=305,
  serialized_end=467,
)


_CONTROLRELAYPACKET = _descriptor.Descriptor(
  name='ControlRelayPacket',
  full_name='control_relay_service.v1.ControlRelayPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_name', full_name='control_relay_service.v1.ControlRelayPacket.device_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='device_interface', full_name='control_relay_service.v1.ControlRelayPacket.device_interface', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='originating_rule', full_name='control_relay_service.v1.ControlRelayPacket.originating_rule', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='packet', full_name='control_relay_service.v1.ControlRelayPacket.packet', index=3,
      number=10, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=469,
  serialized_end=578,
)

_HELLOREQUEST.fields_by_name['controller'].message_type = _CONTROLLERHELLO
_HELLOREQUEST.fields_by_name['device'].message_type = _DEVICEHELLO
_HELLOREQUEST.oneofs_by_name['local_endpoint_hello'].fields.append(
  _HELLOREQUEST.fields_by_name['controller'])
_HELLOREQUEST.fields_by_name['controller'].containing_oneof = _HELLOREQUEST.oneofs_by_name['local_endpoint_hello']
_HELLOREQUEST.oneofs_by_name['local_endpoint_hello'].fields.append(
  _HELLOREQUEST.fields_by_name['device'])
_HELLOREQUEST.fields_by_name['device'].containing_oneof = _HELLOREQUEST.oneofs_by_name['local_endpoint_hello']
_HELLORESPONSE.fields_by_name['controller'].message_type = _CONTROLLERHELLO
_HELLORESPONSE.fields_by_name['device'].message_type = _DEVICEHELLO
_HELLORESPONSE.oneofs_by_name['remote_endpoint_hello'].fields.append(
  _HELLORESPONSE.fields_by_name['controller'])
_HELLORESPONSE.fields_by_name['controller'].containing_oneof = _HELLORESPONSE.oneofs_by_name['remote_endpoint_hello']
_HELLORESPONSE.oneofs_by_name['remote_endpoint_hello'].fields.append(
  _HELLORESPONSE.fields_by_name['device'])
_HELLORESPONSE.fields_by_name['device'].containing_oneof = _HELLORESPONSE.oneofs_by_name['remote_endpoint_hello']
DESCRIPTOR.message_types_by_name['ControllerHello'] = _CONTROLLERHELLO
DESCRIPTOR.message_types_by_name['DeviceHello'] = _DEVICEHELLO
DESCRIPTOR.message_types_by_name['HelloRequest'] = _HELLOREQUEST
DESCRIPTOR.message_types_by_name['HelloResponse'] = _HELLORESPONSE
DESCRIPTOR.message_types_by_name['ControlRelayPacket'] = _CONTROLRELAYPACKET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ControllerHello = _reflection.GeneratedProtocolMessageType('ControllerHello', (_message.Message,), {
  'DESCRIPTOR' : _CONTROLLERHELLO,
  '__module__' : 'control_relay_service_pb2'
  # @@protoc_insertion_point(class_scope:control_relay_service.v1.ControllerHello)
  })
_sym_db.RegisterMessage(ControllerHello)

DeviceHello = _reflection.GeneratedProtocolMessageType('DeviceHello', (_message.Message,), {
  'DESCRIPTOR' : _DEVICEHELLO,
  '__module__' : 'control_relay_service_pb2'
  # @@protoc_insertion_point(class_scope:control_relay_service.v1.DeviceHello)
  })
_sym_db.RegisterMessage(DeviceHello)

HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQUEST,
  '__module__' : 'control_relay_service_pb2'
  # @@protoc_insertion_point(class_scope:control_relay_service.v1.HelloRequest)
  })
_sym_db.RegisterMessage(HelloRequest)

HelloResponse = _reflection.GeneratedProtocolMessageType('HelloResponse', (_message.Message,), {
  'DESCRIPTOR' : _HELLORESPONSE,
  '__module__' : 'control_relay_service_pb2'
  # @@protoc_insertion_point(class_scope:control_relay_service.v1.HelloResponse)
  })
_sym_db.RegisterMessage(HelloResponse)

ControlRelayPacket = _reflection.GeneratedProtocolMessageType('ControlRelayPacket', (_message.Message,), {
  'DESCRIPTOR' : _CONTROLRELAYPACKET,
  '__module__' : 'control_relay_service_pb2'
  # @@protoc_insertion_point(class_scope:control_relay_service.v1.ControlRelayPacket)
  })
_sym_db.RegisterMessage(ControlRelayPacket)



_CONTROLRELAYHELLOSERVICE = _descriptor.ServiceDescriptor(
  name='ControlRelayHelloService',
  full_name='control_relay_service.v1.ControlRelayHelloService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=580,
  serialized_end=698,
  methods=[
  _descriptor.MethodDescriptor(
    name='Hello',
    full_name='control_relay_service.v1.ControlRelayHelloService.Hello',
    index=0,
    containing_service=None,
    input_type=_HELLOREQUEST,
    output_type=_HELLORESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONTROLRELAYHELLOSERVICE)

DESCRIPTOR.services_by_name['ControlRelayHelloService'] = _CONTROLRELAYHELLOSERVICE


_CONTROLRELAYPACKETSERVICE = _descriptor.ServiceDescriptor(
  name='ControlRelayPacketService',
  full_name='control_relay_service.v1.ControlRelayPacketService',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=701,
  serialized_end=907,
  methods=[
  _descriptor.MethodDescriptor(
    name='PacketTx',
    full_name='control_relay_service.v1.ControlRelayPacketService.PacketTx',
    index=0,
    containing_service=None,
    input_type=_CONTROLRELAYPACKET,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ListenForPacketRx',
    full_name='control_relay_service.v1.ControlRelayPacketService.ListenForPacketRx',
    index=1,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_CONTROLRELAYPACKET,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONTROLRELAYPACKETSERVICE)

DESCRIPTOR.services_by_name['ControlRelayPacketService'] = _CONTROLRELAYPACKETSERVICE

# @@protoc_insertion_point(module_scope)
