# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import tr477_cpri_message_pb2 as tr477__cpri__message__pb2


class CpriMessageStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ListenForCpriRx = channel.unary_stream(
        '/tr477_cpri_message.v1.CpriMessage/ListenForCpriRx',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=tr477__cpri__message__pb2.CpriMsg.FromString,
        )
    self.CpriTx = channel.unary_unary(
        '/tr477_cpri_message.v1.CpriMessage/CpriTx',
        request_serializer=tr477__cpri__message__pb2.CpriMsg.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )


class CpriMessageServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ListenForCpriRx(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CpriTx(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CpriMessageServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ListenForCpriRx': grpc.unary_stream_rpc_method_handler(
          servicer.ListenForCpriRx,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=tr477__cpri__message__pb2.CpriMsg.SerializeToString,
      ),
      'CpriTx': grpc.unary_unary_rpc_method_handler(
          servicer.CpriTx,
          request_deserializer=tr477__cpri__message__pb2.CpriMsg.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'tr477_cpri_message.v1.CpriMessage', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
