# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tr477_cpri_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import tr477_cpri_message_pb2 as tr477__cpri__message__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tr477_cpri_service.proto',
  package='tr477_cpri_message.v1',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x18tr477_cpri_service.proto\x12\x15tr477_cpri_message.v1\x1a\x18tr477_cpri_message.proto\x1a\x1bgoogle/protobuf/empty.proto2\x9c\x01\n\x0b\x43priMessage\x12K\n\x0fListenForCpriRx\x12\x16.google.protobuf.Empty\x1a\x1e.tr477_cpri_message.v1.CpriMsg0\x01\x12@\n\x06\x43priTx\x12\x1e.tr477_cpri_message.v1.CpriMsg\x1a\x16.google.protobuf.Emptyb\x06proto3')
  ,
  dependencies=[tr477__cpri__message__pb2.DESCRIPTOR,google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_CPRIMESSAGE = _descriptor.ServiceDescriptor(
  name='CpriMessage',
  full_name='tr477_cpri_message.v1.CpriMessage',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=107,
  serialized_end=263,
  methods=[
  _descriptor.MethodDescriptor(
    name='ListenForCpriRx',
    full_name='tr477_cpri_message.v1.CpriMessage.ListenForCpriRx',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=tr477__cpri__message__pb2._CPRIMSG,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CpriTx',
    full_name='tr477_cpri_message.v1.CpriMessage.CpriTx',
    index=1,
    containing_service=None,
    input_type=tr477__cpri__message__pb2._CPRIMSG,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CPRIMESSAGE)

DESCRIPTOR.services_by_name['CpriMessage'] = _CPRIMESSAGE

# @@protoc_insertion_point(module_scope)
