// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.6.1
// source: tr477_cpri_message.proto

//**************************************************************************
// TR-477 Control Packet Redirect Interface Message Protocol Buffer Schema
//
//  Copyright (c) 2021, Broadband Forum
//
//  Redistribution and use in source and binary forms, with or
//   without modification, are permitted provided that the following
//   conditions are met:
//
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//
//   2. Redistributions in binary form must reproduce the above
//      copyright notice, this list of conditions and the following
//      disclaimer in the documentation and/or other materials
//      provided with the distribution.
//
//   3. Neither the name of the copyright holder nor the names of its
//      contributors may be used to endorse or promote products
//      derived from this software without specific prior written
//      permission.
//
//   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
//   CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
//   INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
//   MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
//   DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
//   CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
//   SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
//   NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
//   CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
//   STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
//   ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
//   ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
//   The above license is used as a license under copyright only.
//   Please reference the Forum IPR Policy for patent licensing terms
//   <https://www.broadband-forum.org/ipr-policy>.
//
//   Any moral rights which are necessary to exercise under the above
//   license grant are also deemed granted under this license.
//
// | Version           | Name                   | Date       |
// | TR-477 1.0.0      | xxx                    | TBD, 2022  |
//
// BBF software release registry: http://www.broadband-forum.org/software
//**************************************************************************

package pb

import (
	_ "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CpriMsgHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgId string `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"` // Message identifier to
}

func (x *CpriMsgHeader) Reset() {
	*x = CpriMsgHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tr477_cpri_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CpriMsgHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpriMsgHeader) ProtoMessage() {}

func (x *CpriMsgHeader) ProtoReflect() protoreflect.Message {
	mi := &file_tr477_cpri_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpriMsgHeader.ProtoReflect.Descriptor instead.
func (*CpriMsgHeader) Descriptor() ([]byte, []int) {
	return file_tr477_cpri_message_proto_rawDescGZIP(), []int{0}
}

func (x *CpriMsgHeader) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

type GenericMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceName string `protobuf:"bytes,1,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"` //The name of the device where the packet was
	//intercepted/is destined to
	DeviceInterface string `protobuf:"bytes,2,opt,name=device_interface,json=deviceInterface,proto3" json:"device_interface,omitempty"` //The name of the interface where the packet
	//was intercepted/is destined to
	OriginatingRule string `protobuf:"bytes,3,opt,name=originating_rule,json=originatingRule,proto3" json:"originating_rule,omitempty"` //Optional identification of the rule that originated the
}

func (x *GenericMetadata) Reset() {
	*x = GenericMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tr477_cpri_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenericMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericMetadata) ProtoMessage() {}

func (x *GenericMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_tr477_cpri_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericMetadata.ProtoReflect.Descriptor instead.
func (*GenericMetadata) Descriptor() ([]byte, []int) {
	return file_tr477_cpri_message_proto_rawDescGZIP(), []int{1}
}

func (x *GenericMetadata) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *GenericMetadata) GetDeviceInterface() string {
	if x != nil {
		return x.DeviceInterface
	}
	return ""
}

func (x *GenericMetadata) GetOriginatingRule() string {
	if x != nil {
		return x.OriginatingRule
	}
	return ""
}

type OnuMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChannelTermination string `protobuf:"bytes,1,opt,name=channel_termination,json=channelTermination,proto3" json:"channel_termination,omitempty"` //The local name of the channel termination
	//in the OLT where the ONU is attached
	OnuId string `protobuf:"bytes,2,opt,name=onu_id,json=onuId,proto3" json:"onu_id,omitempty"` //ITU-T Transmission Convergence (TC)
}

func (x *OnuMetadata) Reset() {
	*x = OnuMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tr477_cpri_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnuMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnuMetadata) ProtoMessage() {}

func (x *OnuMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_tr477_cpri_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnuMetadata.ProtoReflect.Descriptor instead.
func (*OnuMetadata) Descriptor() ([]byte, []int) {
	return file_tr477_cpri_message_proto_rawDescGZIP(), []int{2}
}

func (x *OnuMetadata) GetChannelTermination() string {
	if x != nil {
		return x.ChannelTermination
	}
	return ""
}

func (x *OnuMetadata) GetOnuId() string {
	if x != nil {
		return x.OnuId
	}
	return ""
}

type DhcpMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DhcpMetadata) Reset() {
	*x = DhcpMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tr477_cpri_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DhcpMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DhcpMetadata) ProtoMessage() {}

func (x *DhcpMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_tr477_cpri_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DhcpMetadata.ProtoReflect.Descriptor instead.
func (*DhcpMetadata) Descriptor() ([]byte, []int) {
	return file_tr477_cpri_message_proto_rawDescGZIP(), []int{3}
}

type PppoeMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PppoeMetadata) Reset() {
	*x = PppoeMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tr477_cpri_message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PppoeMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PppoeMetadata) ProtoMessage() {}

func (x *PppoeMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_tr477_cpri_message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PppoeMetadata.ProtoReflect.Descriptor instead.
func (*PppoeMetadata) Descriptor() ([]byte, []int) {
	return file_tr477_cpri_message_proto_rawDescGZIP(), []int{4}
}

type CpriMetaData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Generic *GenericMetadata `protobuf:"bytes,1,opt,name=generic,proto3" json:"generic,omitempty"` //Common generic metadata
	Onu     *OnuMetadata     `protobuf:"bytes,2,opt,name=onu,proto3" json:"onu,omitempty"`         //Optional information about the ONU that
	//originated the packet or is destination
	//for the packet
	//
	// Types that are assignable to SpecificMetadata:
	//	*CpriMetaData_Dhcp
	//	*CpriMetaData_Pppoe
	SpecificMetadata isCpriMetaData_SpecificMetadata `protobuf_oneof:"specific_metadata"`
}

func (x *CpriMetaData) Reset() {
	*x = CpriMetaData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tr477_cpri_message_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CpriMetaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpriMetaData) ProtoMessage() {}

func (x *CpriMetaData) ProtoReflect() protoreflect.Message {
	mi := &file_tr477_cpri_message_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpriMetaData.ProtoReflect.Descriptor instead.
func (*CpriMetaData) Descriptor() ([]byte, []int) {
	return file_tr477_cpri_message_proto_rawDescGZIP(), []int{5}
}

func (x *CpriMetaData) GetGeneric() *GenericMetadata {
	if x != nil {
		return x.Generic
	}
	return nil
}

func (x *CpriMetaData) GetOnu() *OnuMetadata {
	if x != nil {
		return x.Onu
	}
	return nil
}

func (m *CpriMetaData) GetSpecificMetadata() isCpriMetaData_SpecificMetadata {
	if m != nil {
		return m.SpecificMetadata
	}
	return nil
}

func (x *CpriMetaData) GetDhcp() *DhcpMetadata {
	if x, ok := x.GetSpecificMetadata().(*CpriMetaData_Dhcp); ok {
		return x.Dhcp
	}
	return nil
}

func (x *CpriMetaData) GetPppoe() *PppoeMetadata {
	if x, ok := x.GetSpecificMetadata().(*CpriMetaData_Pppoe); ok {
		return x.Pppoe
	}
	return nil
}

type isCpriMetaData_SpecificMetadata interface {
	isCpriMetaData_SpecificMetadata()
}

type CpriMetaData_Dhcp struct {
	Dhcp *DhcpMetadata `protobuf:"bytes,3,opt,name=dhcp,proto3,oneof"`
}

type CpriMetaData_Pppoe struct {
	Pppoe *PppoeMetadata `protobuf:"bytes,4,opt,name=pppoe,proto3,oneof"`
}

func (*CpriMetaData_Dhcp) isCpriMetaData_SpecificMetadata() {}

func (*CpriMetaData_Pppoe) isCpriMetaData_SpecificMetadata() {}

type CpriMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header   *CpriMsgHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	MetaData *CpriMetaData  `protobuf:"bytes,2,opt,name=meta_data,json=metaData,proto3" json:"meta_data,omitempty"`
	Packet   []byte         `protobuf:"bytes,3,opt,name=packet,proto3" json:"packet,omitempty"` //Unmodified contents of the packet
}

func (x *CpriMsg) Reset() {
	*x = CpriMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tr477_cpri_message_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CpriMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpriMsg) ProtoMessage() {}

func (x *CpriMsg) ProtoReflect() protoreflect.Message {
	mi := &file_tr477_cpri_message_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpriMsg.ProtoReflect.Descriptor instead.
func (*CpriMsg) Descriptor() ([]byte, []int) {
	return file_tr477_cpri_message_proto_rawDescGZIP(), []int{6}
}

func (x *CpriMsg) GetHeader() *CpriMsgHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *CpriMsg) GetMetaData() *CpriMetaData {
	if x != nil {
		return x.MetaData
	}
	return nil
}

func (x *CpriMsg) GetPacket() []byte {
	if x != nil {
		return x.Packet
	}
	return nil
}

var File_tr477_cpri_message_proto protoreflect.FileDescriptor

var file_tr477_cpri_message_proto_rawDesc = []byte{
	0x0a, 0x18, 0x74, 0x72, 0x34, 0x37, 0x37, 0x5f, 0x63, 0x70, 0x72, 0x69, 0x5f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x74, 0x72, 0x34, 0x37,
	0x37, 0x5f, 0x63, 0x70, 0x72, 0x69, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x76,
	0x31, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x26,
	0x0a, 0x0d, 0x43, 0x70, 0x72, 0x69, 0x4d, 0x73, 0x67, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12,
	0x15, 0x0a, 0x06, 0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x22, 0x88, 0x01, 0x0a, 0x0f, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x69, 0x63, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x64,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e,
	0x61, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x72, 0x75, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0f, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x75, 0x6c,
	0x65, 0x22, 0x55, 0x0a, 0x0b, 0x4f, 0x6e, 0x75, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x12, 0x2f, 0x0a, 0x13, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x74, 0x65, 0x72, 0x6d,
	0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x63,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x15, 0x0a, 0x06, 0x6f, 0x6e, 0x75, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x6f, 0x6e, 0x75, 0x49, 0x64, 0x22, 0x0e, 0x0a, 0x0c, 0x44, 0x68, 0x63, 0x70,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x22, 0x0f, 0x0a, 0x0d, 0x50, 0x70, 0x70, 0x6f,
	0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x22, 0x94, 0x02, 0x0a, 0x0c, 0x43, 0x70,
	0x72, 0x69, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x12, 0x40, 0x0a, 0x07, 0x67, 0x65,
	0x6e, 0x65, 0x72, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x74, 0x72,
	0x34, 0x37, 0x37, 0x5f, 0x63, 0x70, 0x72, 0x69, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x52, 0x07, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x12, 0x34, 0x0a, 0x03,
	0x6f, 0x6e, 0x75, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x74, 0x72, 0x34, 0x37,
	0x37, 0x5f, 0x63, 0x70, 0x72, 0x69, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x4f, 0x6e, 0x75, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x03, 0x6f,
	0x6e, 0x75, 0x12, 0x39, 0x0a, 0x04, 0x64, 0x68, 0x63, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x23, 0x2e, 0x74, 0x72, 0x34, 0x37, 0x37, 0x5f, 0x63, 0x70, 0x72, 0x69, 0x5f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x68, 0x63, 0x70, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x04, 0x64, 0x68, 0x63, 0x70, 0x12, 0x3c, 0x0a,
	0x05, 0x70, 0x70, 0x70, 0x6f, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x74,
	0x72, 0x34, 0x37, 0x37, 0x5f, 0x63, 0x70, 0x72, 0x69, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x70, 0x70, 0x6f, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x48, 0x00, 0x52, 0x05, 0x70, 0x70, 0x70, 0x6f, 0x65, 0x42, 0x13, 0x0a, 0x11, 0x73,
	0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x22, 0xa1, 0x01, 0x0a, 0x07, 0x43, 0x70, 0x72, 0x69, 0x4d, 0x73, 0x67, 0x12, 0x3c, 0x0a, 0x06,
	0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x74,
	0x72, 0x34, 0x37, 0x37, 0x5f, 0x63, 0x70, 0x72, 0x69, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x70, 0x72, 0x69, 0x4d, 0x73, 0x67, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x40, 0x0a, 0x09, 0x6d, 0x65,
	0x74, 0x61, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e,
	0x74, 0x72, 0x34, 0x37, 0x37, 0x5f, 0x63, 0x70, 0x72, 0x69, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x70, 0x72, 0x69, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06,
	0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x70, 0x61,
	0x63, 0x6b, 0x65, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tr477_cpri_message_proto_rawDescOnce sync.Once
	file_tr477_cpri_message_proto_rawDescData = file_tr477_cpri_message_proto_rawDesc
)

func file_tr477_cpri_message_proto_rawDescGZIP() []byte {
	file_tr477_cpri_message_proto_rawDescOnce.Do(func() {
		file_tr477_cpri_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_tr477_cpri_message_proto_rawDescData)
	})
	return file_tr477_cpri_message_proto_rawDescData
}

var file_tr477_cpri_message_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_tr477_cpri_message_proto_goTypes = []interface{}{
	(*CpriMsgHeader)(nil),   // 0: tr477_cpri_message.v1.CpriMsgHeader
	(*GenericMetadata)(nil), // 1: tr477_cpri_message.v1.GenericMetadata
	(*OnuMetadata)(nil),     // 2: tr477_cpri_message.v1.OnuMetadata
	(*DhcpMetadata)(nil),    // 3: tr477_cpri_message.v1.DhcpMetadata
	(*PppoeMetadata)(nil),   // 4: tr477_cpri_message.v1.PppoeMetadata
	(*CpriMetaData)(nil),    // 5: tr477_cpri_message.v1.CpriMetaData
	(*CpriMsg)(nil),         // 6: tr477_cpri_message.v1.CpriMsg
}
var file_tr477_cpri_message_proto_depIdxs = []int32{
	1, // 0: tr477_cpri_message.v1.CpriMetaData.generic:type_name -> tr477_cpri_message.v1.GenericMetadata
	2, // 1: tr477_cpri_message.v1.CpriMetaData.onu:type_name -> tr477_cpri_message.v1.OnuMetadata
	3, // 2: tr477_cpri_message.v1.CpriMetaData.dhcp:type_name -> tr477_cpri_message.v1.DhcpMetadata
	4, // 3: tr477_cpri_message.v1.CpriMetaData.pppoe:type_name -> tr477_cpri_message.v1.PppoeMetadata
	0, // 4: tr477_cpri_message.v1.CpriMsg.header:type_name -> tr477_cpri_message.v1.CpriMsgHeader
	5, // 5: tr477_cpri_message.v1.CpriMsg.meta_data:type_name -> tr477_cpri_message.v1.CpriMetaData
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_tr477_cpri_message_proto_init() }
func file_tr477_cpri_message_proto_init() {
	if File_tr477_cpri_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tr477_cpri_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CpriMsgHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tr477_cpri_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenericMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tr477_cpri_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnuMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tr477_cpri_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DhcpMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tr477_cpri_message_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PppoeMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tr477_cpri_message_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CpriMetaData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tr477_cpri_message_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CpriMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_tr477_cpri_message_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*CpriMetaData_Dhcp)(nil),
		(*CpriMetaData_Pppoe)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tr477_cpri_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tr477_cpri_message_proto_goTypes,
		DependencyIndexes: file_tr477_cpri_message_proto_depIdxs,
		MessageInfos:      file_tr477_cpri_message_proto_msgTypes,
	}.Build()
	File_tr477_cpri_message_proto = out.File
	file_tr477_cpri_message_proto_rawDesc = nil
	file_tr477_cpri_message_proto_goTypes = nil
	file_tr477_cpri_message_proto_depIdxs = nil
}
